
services:
    mysql:
        container_name: mysql
        hostname: mysql        
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=productdb
        ports:
            - 3305:3306    
        networks:
            - spring-network      
    
    eureka:
        container_name: eureka-server
        hostname: eureka-server
        image: 8357/spring-k8-eureka:1.0.0
        restart: always 
        ports:
            - 8700:8761
        networks:
            - spring-network
    product-service:
        links:
            - mysql
        container_name: product-service
        image: 8357/product-service:1.0.0
        restart: always
        environment: 
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - EUREKA_HOST_NAME=eureka-server
        ports:
            - 8080:8080      
        networks:
            - spring-network
    payment-service:
        links:
            - mysql
        container_name: payment-service
        image: 8357/payment-service:1.0.0
        restart: always
        environment: 
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - EUREKA_HOST_NAME=eureka-server
        ports:
            - 8081:8081      
        networks:
            - spring-network
    order-service:
        links:
            - mysql
        container_name: order-service
        image: 8357/order-service:1.0.0
        restart: always
        environment: 
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - EUREKA_HOST_NAME=eureka-server
        ports:
            - 8082:8082      
        networks:
            - spring-network        
networks:
  spring-network:
    driver: bridge