server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
#  autoconfigure:
#    exclude:
#    - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
